#!/usr/bin/env bash
#
# test
#

# go to own dir
cd "$(dirname "$BASH_SOURCE")"

# vars
vpkg_profile=".vpkgrc"
vpkg_conf_file=".vpkg"
expected=29
t=1

# some helpers

tap() {
  if [ $? = 0 ]
  then
    echo "✔  passed test #$t: $1"
  else
    echo "✘  failed test #$t: $1" >&2
    summarize
    exit 1
  fi
  ((t++))
}

check_version() {
  # strip version of leading, non-number characters
  v="$(echo "$1" | sed "s/[^0-9]*\(.*\)/\1/")"
  test "$v" = "$2"
  tap "$v = $2 - $3"
}

summarize() {
  [ $((--t)) = $expected ] && status="success" || status="failure"
  echo ""
  echo "------------------ $status ------------------"
  echo "$t of $expected tests passed"
}

teardown() {
  rm -rf tmp
}


# test bootstrapping
test_bootstrap() {
  teardown
  
  # download vpkgfile
  repo="file://$(pwd)/.."
  url="$repo"/"$vpkg_conf_file"
  echo "downloading $url..."
  hooks="$(curl -f# "$url")"
  tap "download $vpkg_conf_file"
  hooks="$(echo "$hooks" | sed "s|repo=\".*|repo=\"$repo\"|")"  # use local repo for testing
  
  # bootstrap
  mkdir tmp
  (
    eval "$hooks"
    bootstrap "$(pwd)"/tmp
  )
  tap "bootstrap - create dirs and config"
  
  # source fresh config
  source tmp/"$vpkg_profile"
  tap "bootstrap - validate config"
  
  # check our binary linked properly
  test "$(which vpkg)" = "$VPKG_ROOT/bin/vpkg"
  tap "bootstrap - test vpkg link"
  
  # include the vpkg function library
  source tmp/lib/vpkg/current/lib/functions
  tap "bootstrap - include vpkg function library"
}

# conf file tests
test_conf() {
  
  # install
  echo "file://$(pwd)/fixtures/node/$vpkg_conf_file" | vpkg install node
  tap "install node"
  
  # install alt
  vpkg install node 0.8.6
  tap "install node 0.8.6"
  
  # install custom
  vpkg install node development 0.9.9
  tap "install node custom version 'development' from 0.9.9"
  
  # link
  vpkg link node 0.8.6
  tap "link node 0.8.6"
  check_version "$(node -v)" "0.8.6" "check link version"
  test "$(which node)" = "$VPKG_ROOT"/bin/node
  tap "confirm link"
  
  # link
  vpkg link node development
  tap "link node development (0.9.9)"
  check_version "$(node -v)" "0.9.9" "check link version"
  test ! -e "$VPKG_ROOT"/bin/node-waf
  tap "confirm 0.8.6 was unlinked (0.9.9 does not include node-waf)"
  
  # use
  vpkg-use node 0.8.20
  tap "use node 0.8.20"
  check_version "$(node -v)" "0.8.20" "check use version"

  # unuse
  vpkg-unuse node 0.8.20
  tap "unuse node 0.8.20"
  check_version "$(node -v)" "0.9.9" "check unuse version"
  
  # uninstall
  vpkg uninstall node development
  tap "uninstall node development"
  test "$(which node)" != "$VPKG_ROOT"/bin/node
  tap "confirm uninstall also unlinked"
  
  # link again
  vpkg link node 0.8.6
  tap "relink node 0.8.6"
  
  # test version specify unlink
  vpkg unlink node 0.8.6
  tap "unlink node 0.8.6"
  test "$(which node)" != "$VPKG_ROOT"/bin/node
  tap "confirm unlink"
  
  # leave node 0.8.20 linked
  vpkg link node 0.8.20
  tap "relink node 0.8.20"
}

# sans vpkgfile
test_raw() {
  
  # setup (pretend we created this package by hand)
  src="$VPKG_ROOT"/src
  mkdir -p "$src"
  cp -R fixtures/raw-src "$src"
  
  # install
  vpkg install raw-src 0.0.1
  tap "install raw-src 0.0.1"
  
  # alt
  vpkg install raw-src 0.0.2
  tap "install raw-src 0.0.2"
  
  # link 
  vpkg link raw-src 0.0.1
  tap "link raw-src 0.0.1"
  check_version "$(raw-src --version)" "0.0.1" "check link version"
  test "$(which raw-src)" = "$VPKG_ROOT"/bin/raw-src
  tap "confirm link"
}

# test bootstrapping
test_bootstrap

# test a package with conf
test_conf

# test a package with no conf
test_raw

# display a summary if we made it this far
summarize
