#!/usr/bin/env bash
#
# vpkgfile
#

# repo location
REPO_URL="file:///Users/jessetane/Desktop/vpkg/lib/vpkg/src"
DEFAULT_NAME="vpkg"
DEFAULT_VERSION="0.0.2"

bail() {
  echo "$1" >&2
  exit 1
}

gen_config() {
  name="$1"
  uppercase_name="$(echo "$name" | awk '{ print toupper($1) }')"
  echo '#
# .'"$name"'
#

# get root
root="$(cd "$(dirname "$BASH_SOURCE")" && pwd)"

# pkg root
export '"$uppercase_name"'_ROOT="$root"

# add bin to PATH
export PATH="$'"$uppercase_name"'_ROOT"/bin:"$PATH"
'
}

common() {
  
  # require $VPKG_ROOT
  [ -z "$VPKG_ROOT" ] && bail '$VPKG_ROOT must be defined'
  
  # args
  name="$1"
  version="$2"
  sourceVersion="$3"
  
  # defaults
  [ -z "$name" ] && name="$DEFAULT_NAME"
  [ -z "$version" ] && version="$DEFAULT_VERSION"
  [ -z "$sourceVersion" ] && sourceVersion="$version"
}

install() {
  
  # setup args
  common "$@"
  
  # we have source code?
  src="$VPKG_ROOT"/lib/"$name"/src
  if [ ! -e "$src" ]
  then
    git clone "$REPO_URL" "$src"
  fi
  
  # update
  cd "$src"
  git fetch --all
  git fetch --tags
  
  # version
  git checkout "$sourceVersion"
  
  # install
  mkdir -p ../versions
  cp -R . ../versions/"$version"
}

bootstrap() {
  
  # args
  root="$1"
  name="$DEFAULT_NAME"
  version="$DEFAULT_VERSION"
  
  # default to pwd
  [ -z "$root" ] && bail "please specify a directory to bootstrap into"
  
  # make some dirs
  mkdir -p "$root"/bin
  mkdir -p "$root"/lib/"$name"
  
  # autogenerate a sourceable config
  # file and just put it in the root
  gen_config "$name" > "$root/.$name"

  # source the config file
  source "$root/.$name"
  
  # install default version of self
  install "$name" "$version"
  
  # ref to executable
  bin="$root"/lib/"$name"/versions/"$version"/bin/"$name"
  
  # how meta: use the vpkg tool to link itself...
  "$bin" link "$name" "$version"
}

# require at least one argument
[ "$#" = 0 ] && echo "please specify a command" >&2 && exit 127

# run
"$1" "${@:2}"
