#!/usr/bin/env bash
#
# vpkgfile
#

bail() {
  echo "$1" >&2
  exit 1
}

gen_profile() {
  echo '#
# .profile - you could source this from your user .profile
#

# pkg root
export VPKG_ROOT="'"$1"'"

# add bin to PATH
export PATH="$VPKG_ROOT"/bin:"$PATH"
'
}

common() {
  
  # args
  name="$1"
  version="$2"
  sourceVersion="$3"
  
  # require $VPKG_ROOT
  [ -z "$VPKG_ROOT" ] && bail '$VPKG_ROOT must be defined'
  [ -z "$name" ] && bail '$name must be defined'
  
  # defaults
  [ -z "$version" ] && version="$default_version"
  [ -z "$sourceVersion" ] && sourceVersion="$version"
}

install() {
  
  # setup args
  common "$@"
  
  # we have source code?
  src="$VPKG_ROOT"/lib/"$name"/src
  if [ ! -e "$src" ]
  then
    git clone "$repo" "$src"
  fi
  
  # update
  cd "$src"
  git fetch --all
  git fetch --tags
  
  # version
  git checkout "$sourceVersion"
  
  # install
  mkdir -p ../versions
  cp -R . ../versions/"$version"
}

bootstrap() {
  
  # args
  root="$1"
  name="vpkg"
  
  # default to pwd
  [ -z "$root" ] && bail "please specify a directory to bootstrap into"
  
  # make some dirs
  mkdir -p "$root"/bin
  mkdir -p "$root"/lib/"$name"
  
  # autogenerate a sourceable profile
  # file and just put it in the root
  gen_profile "$root" > "$root/.profile"
  
  # source the config file
  source "$root/.profile"
  
  # install default version of self
  install "$name" "$version"
  
  # ref to executable
  bin="$root"/lib/"$name"/versions/"$version"/bin/"$name"
  
  # how meta: use the vpkg tool to link itself...
  "$bin" link "$name" "$version"
}

# vars
default_version="0.0.2"
repo="https://github.com/jessetane/vpkg"

# args
cmd="$1"
args="${@:2}"

# run
"$cmd" "$args"
